version: "2"
services:
  minio:
    image: minio/minio
    command: server /data
    ports: ["9000:9000"]
    volumes:
    - "./minio/config:/root/.minio"
    - "./kit:/data"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: alwaysbekind

  concourse-db:
    image: postgres:9.5
    volumes:
    - ./concourse/data:/database
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: alwaysbekind
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    depends_on:
    - concourse-db
    links:
    - concourse-db
    command: web
    ports: ["8080:8080"]
    volumes: ["./concourse/keys/web:/concourse-keys"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: alwaysbekind
      CONCOURSE_EXTERNAL_URL: "http://pcfbuild:8080"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:alwaysbekind@concourse-db:5432/concourse?sslmode=disable

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    command: worker
    volumes: ["./concourse/keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
