pivnet_token:

github_username:
github_token:

# Get the product slug from the URI at https://network.pivotal.io
# For example, "p-redis" found in https://network.pivotal.io/products/p-redis
product_slug: elastic-runtime
product_version: 1.10.*
pivnet_glob: '*pivotal'

s3_access_key:
s3_secret_key:
s3_endpoint: https://s3.amazon.com
s3_output_bucket:
s3_region: us-east-1

# for opsmgr, file_extension use below
# file_extension: 'pivnet-product/*.ova'
file_regexp: '-(.*)-'
