resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: offline-pivnet
  type: git
  source:
    branch: master
    uri: https://github.com/pivotalservices/offline-pivnet.git

- name: pivnet-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: {{product_slug}}
    product_version: {{product_version}}
    sort_by: semver

- name: s3
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{s3_access_key}}
    secret_access_key: {{s3_secret_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_output_bucket}}
    region_name: {{s3_region}}

jobs:
- name: upload
  serial: true
  plan:
  - get: offline-pivnet
  - get: pivnet-product
    resource: pivnet-product
    trigger: true
    params:
      globs:
      - {{pivnet_glob}}
  - task: upload
    file: pcf-pipelines/tasks/prepare-pivnet-products
    params:
      s3_access_key: {{s3_access_key}}
      s3_secret_key: {{s3_secret_key}}
      s3_endpoint: {{s3_endpoint}}
      s3_output_bucket: {{s3_output_bucket}}
      s3_region: {{s3_region}}
  - put: s3
    params:
      file: -(.*)-
