---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: offline-concourse-tools
  - name: pivnet-cli
  - name: minio-client
  - name: jq
outputs:
  - name: minio_data
params:
  PIVNET_TOKEN:
  PIVNET_PRODUCT_SLUGS:
  PIVNET_PRODUCT_VERSIONS:
  PIVNET_PRODUCT_FILES:
run:
  path: offline-pivnet/scripts/prepare-pivnet-products.sh
