---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: offline-pivnet
  - name: pivnet-cli
  - name: minio-client
  - name: jq
outputs:
  - name: s3
params:
  PIVNET_TOKEN:
  S3_ACCESS_KEY:
  S3_SECRET_KEY:
  S3_ENDPOINT:
  S3_OUTPUT_BUCKET:
  S3_REGION:
run:
  path: offline-pivnet/scripts/prepare-pivnet-products.sh
