pivnet_token: 
github_token: 
s3_access_key_id: minio
s3_secret_access_key: alwaysbekind
s3_endpoint: http://minio:9000
s3_bucket: products
s3_region: us-east-1

iaas_type: vsphere

# Pivotal product tiles

mysql_v1_version_regex: ^1\..*\..*$
mysql_v2_version_regex: ^2\..*\..*$
sso_version_regex: ^1\..*\..*$
pcf_metrics_version_regex: ^1\..*\..*$
cloud_cache_version_regex: ^1\..*\..*$
redis_version_regex: ^1\..*\..*$

# Bosh add-ons

clamav_version_regex: ^1\..*\..*$
fim_version_regex: ^1\..*\..*$
ipsec_version_regex: ^1\..*\..*$
osconf_version_regex: ^.*$

# Bosh Deployments (standalong)

concourse_version_regex: ^3\..*\..*$
